sudo: required # super user level permissions to execute the build
services:
    - docker # this install docker in  travis

before_install:
    - docker build -t sravan13/docker-react -f Dockerfile.dev .  

script:
    - docker run -e CI=true  sravan13/docker-react npm run test